config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get '/en/dashboard', to: 'flats#show'
  resources :flats, except: [:index, :show] do
    resources :expenses, except: [:index]
  end

  resources :expenses, only: [] do
    resources :comments
  end

  get '/profile', to: 'profiles#show'

  get '/fetch_mate', to: 'flats#fetch_mate'
end

app/models/flat.rb
class Flat < ApplicationRecord
  has_many :users, dependent: :nullify
  belongs_to :admin, class_name: 'User', foreign_key: 'user_id'

  has_many :expenses, dependent: :destroy
  after_create :set_admin_as_flatmate
  has_one_attached :photo

  validates :name, presence: true

  def total_expenses
    expenses.reduce(0) { |acc, expense| acc += expense.amount }
  end

  def month_total_expenses(month)
    expenses.where(payment_month: month).reduce(0) { |acc, expense| acc += expense.amount }
  end

  def set_admin_as_flatmate
    admin.flat = self
    admin.save
  end

  def set_users_and_rent(user_emails, rents)
    users.each do |flatmate|
      next if flatmate == admin

      flatmate.flat = nil
      flatmate.rent = nil
      flatmate.save
    end
    return unless user_emails

    user_emails.each_with_index do |email, i|
      user = User.find_by(email: email) || User.invite!(email: email, flat: self, password: "password", password_confirmation: "password")
      user.flat = self
      user.rent = rents[i]
      user.save
    end
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:edit, :update, :destroy]

  def show
    if current_user.flat
      @flat = current_user.flat
      @month = params[:date] ? params[:date][:date] : Expense::MONTHS[Date.today.month - 1]
      authorize @flat
      @monthly_expenses = @flat.expenses.where(payment_month: @month)

      @total_expenses = @flat.month_total_expenses(@month) + @flat.rent
    else
      skip_authorization
      redirect_to new_flat_path
    end
  end

  def new
    @flat = Flat.new
    authorize @flat
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.admin = current_user
    authorize @flat

    if @flat.save
      @flat.set_users_and_rent(params[:flatmate_emails], params[:rent])
      @flat.admin.rent = @flat.users.count == 1 ? @flat.rent : @flat.rent - params[:rent].map(&:to_i).sum
      @flat.admin.save
      redirect_to en_dashboard_path
    else
      render :new
    end
  end

  def update
    if @flat.update(flat_params)
      @flat.set_users_and_rent(params[:flatmate_emails], params[:rent])
      params[:rent] ||= [0]
      @flat.admin.rent = @flat.rent - params[:rent].map(&:to_i).sum
      @flat.admin.save
      redirect_to en_dashboard_path
    else
      render :edit
    end
  end

  def destroy
    delete_flat = Flat.find(params[:id])
    delete_flat.destroy

    redirect_to '/'
  end

  def fetch_mate
    user = User.find_by(email: params[:email])
    user_hash = user ? user.attributes : { email: params[:email] }
    if user && user.photo.attached?
      user_hash["image_url"] = "https://res.cloudinary.com/dinkluxtp/image/upload/#{user.photo.key}.png"
    else
      user_hash["image_url"] = User::DEFAULT_AVATAR
    end

    skip_authorization
    render json: user_hash
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :rent, :photo, :iban)
  end

  def set_flat
    @flat = Flat.find(params[:id])
    authorize @flat
  end
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<%= render '/shared/navbar' %>


<div class="flat-form-wrapper" data-controller="flat">
  <%= simple_form_for(@flat) do |f| %>
    <div class="text-center preview-banner" id="banner"
    style="height: 25vh; z-index: -1; <%= "background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.4)), url(#{@flat.photo.service_url})" if @flat.photo.attached? %>">
    <h1 class="name-header mb-4"><%= @flat.name %> </h1>
    <div class="upload-button-float">
      <%= f.input :photo, as: :file, input_html: { class: 'd-none', id: 'photo-input', data: { action: 'change->flat#updateButtonState', target: 'flat.image' }  }, label: '<i class="fas fa-images"></i>'.html_safe %>
    </div>
</div>
  <div class="container wrapper-dashboard p-4">
    <div class="update-flat-form mb-5">
      <h3>Change the name of the flat</h3>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
      <div class="flat-properties">
        <%= f.input :name, placeholder: 'Introduce a flat name', label: false, wrapper_html: { class: 'w-100' }, input_html: { class: "flat-edit-input w-100", data: { action: 'keyup->flat#updateButtonState', target: 'flat.name' }} %>
      </div>

      <h3>Add or delete flat mates</h3>
      <div class="addflatmates">
        <input id="email-input" class="email-input" data-target="flat.email" type="text" placeholder="Email">
        <input id="rent-input" class="rent-input" data-target="flat.rent" type="text" placeholder="Rent">
        <div data-action="click->flat#fetchMate" class="add-flat-mate">
          <i class="fas fa-plus"></i>
        </div>
      </div>

      <hr class="my-4">

      <div id="user-container" class="user-container" data-target="flat.flatmates">
        <% @flat.users.each do |user| %>
        <div class="new-mate-card position-relative">
          <div class="mate-card-complete">
            <div class="add-mate-card">
              <div class="medium-avatar" style="background-image: url(<%= user.photo_url %>)"></div>

              <p><%= user.first_name || "Flatifyer" %></p>
            </div>
            <p><%= user.rent.to_i %> € </p>
          </div>
          <% if user != @flat.admin %>
          <input type="hidden" name="flatmate_emails[]" value="<%= user.email %>" />
          <input type="hidden" name="rent[]" value="<%= user.rent %>" />
          <i class="fas fa-trash-alt delete-flatmate-link" data-action="click->flat#removeMate"></i>
          <% end %>
        </div>
        <% end %>
      </div>
      <div class="d-flex justify-center">
        <%= link_to 'Delete flat', flat_path(@flat), method: :delete, data: { confirm: 'Are you sure?' }, class: 'deletebtn ' %>
      </div>
    </div>
  </div>
  <div class="fixed-btn">
    <%= f.submit 'SAVE CHANGES', class: 'disabledbtn', disabled: true, data: { target: 'flat.submit' } %>
  </div>

  <% end %>
</div>

app/views/flats/new.html.erb
<%= render '/shared/navbar' %>
<div class="container-flats" data-controller="flat">

  <div class="big-avatar-flat" style="background-image: url(<%= current_user.photo_url %>)"></div>

  <div class="new-flat-page">
    <h1 class="name-header mb-4"><%= current_user.first_name.capitalize %> <%= current_user.last_name.capitalize %> </h1>

    <div class="new-flat-form">
      <h3>Create a new flat</h3>
      <%= simple_form_for(@flat) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <div class="flat-properties">
          <%= f.input :name, placeholder: 'Name of the flat', label: false, input_html: { class: "flat-name-input"} %>
          <%= f.input :rent, placeholder: 'Total rent', label: false, input_html: { class: "flat-rent-input"} %>
        </div>

        <h3 class="mt-2">Add your flat mates</h3>
        <div class="addflatmates">
          <input id="email-input" class="email-input" data-target="flat.email" type="text" placeholder="Email of new mate">
          <input id="rent-input" class="rent-input" data-target="flat.rent" type="text" placeholder="Rent">
          <div data-action="click->flat#fetchMate" class="add-flat-mate"><i class="fas fa-plus"></i></div>
        </div>
        <div id="user-container" class="user-container"></div>
        <div class="fixed-btn">
          <%= f.submit 'Start sharing', class:'primarybtn' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<%= render 'shared/navbar' %>


<div class="container px-4" id="banner" style="<%= "background-image: linear-gradient(to bottom, rgba(76,76,76,0) 0%, rgba(89,89,89,0) 12%, rgba(102,102,102,0) 25%, rgba(89,89,89,0) 31%, rgba(71,71,71,0.09) 39%, rgba(44,44,44,0.22) 50%, rgba(0,0,0,0.23) 51%, rgba(17,17,17,0.34) 60%, rgba(43,43,43,0.53) 76%, rgba(28,28,28,0.7) 91%, rgba(19,19,19,0.81) 100%), url(#{@flat.photo.service_url})" if @flat.photo.attached? %>">
  <div class="flex-banner">
    <div class="d-flex flex-grow-1 align-items-center">
      <div class="balance-card">
        <div class="others-balance"></div>
        <div class="user-balance">
          <h5 class="text-center mb-0">Your balance on <strong><%= @month %></strong></h5>
          <h1 class="text-center mb-0 user-balance-title">-<%= format_cost(current_user.month_total_expenses(@month) + current_user.rent)%>€</h1>
          <h5>Total of the flat: <strong> <%= format_cost(@total_expenses) %>€</strong></h5>
        </div>
      </div>
    </div>
    <div class="flat-info">
      <h2 id="homepage-title"><%= @flat.name.capitalize %></h2>
      <div class="flatmates-container ml-1">
        <% @flat.users.each do |user| %>
          <div class="small-avatar ml-2" style="background-image: url(<%= user.photo_url %>)"></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="wrapper-dashboard pb-5 pt-3">
  <div class="container">

    <div class="expenses-header">
      <h2>Monthly expenses</h2>
      <%= simple_form_for(:date, url: en_dashboard_path, method: :get) do |f| %>
        <%= f.input :date, selected: @month ,collection: Expense::MONTHS, label: false, input_html: { class: 'month-filter', onchange: "this.form.submit()" } %>
      <% end %>
    </div>

    <div class="expenses">
      <% if @monthly_expenses.empty? %>
          <p class="text-center text-secondary">No expenses yet</p>
      <% else %>
        <% @monthly_expenses.reverse.each do |expense| %>
          <%= link_to flat_expense_path(current_user.flat, expense) do  %>
            <div class="card-expense">
              <div class="small-avatar avatar-expense-card" style="background-image: url(<%= expense.creator.photo_url %>)"></div>
              <div class="color-separator expense-category-<%= expense.category.downcase %>"></div>
              <div class="expense-info">
                <h5 class="expense-category mb-0"> <%= expense.category %> </h5>
                <p> <%= expense.created_at.strftime("%m/%d/%Y") %> </p>
              </div>

              <div class="card-price">
                <% if expense.users.include?(current_user) %>
                  <h5 class="amount-to-pay mb-0">- <%= format_cost(expense.amount / expense.users.count).round(2) %>€ </h5>
                  <p class="expense-total-amount mb-0"> <%= format_cost(expense.amount) %> € </p>
                <% else %>
                  <h5 class="expense-total-amount-big mb-0">+ <%= format_cost(expense.amount)%>€ </h5>
                  <p class="expense-total-amount mb-0"> <%= format_cost(expense.amount) %> € </p>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>

  </div>
  <div class="fixed-btn">
    <%= link_to 'Create expense', "/flats/#{current_user.flat.id}/expenses/new", class:'primarybtn btn-fixed' %>
  </div>
</div>