config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get '/en/dashboard', to: 'flats#show'
  resources :flats, except: [:index, :show] do
    resources :expenses, except: [:index]
  end

  resources :expenses, only: [] do
    resources :comments
  end

  get '/profile', to: 'profiles#show'

  get '/fetch_mate', to: 'flats#fetch_mate'
end

app/views/shared/_navbar.html.erb
<nav class='navbar navbar-expand-lg navbar-light bg-light text-center <%="navbar-#{@expense&.category&.downcase}"%>'>
  <%= link_to en_dashboard_path do %>
      <%= cl_image_tag('https://res.cloudinary.com/dinkluxtp/image/upload/v1601551092/flatify-logo-white_jrqrgt.png', alt: "alttext", class: "logo") %>
  <% end %>
  <% if user_signed_in? %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-bars navbar-icon text-white"></i>
    </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to en_dashboard_path do %>
          <h3 class="nav-link mb-0 dashboard-link">Dashboard<span class="sr-only">(current)</span></h3>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to profile_path do %>
          <h3 class="nav-link mb-0 dashboard-link">My profile</h3>
        <% end %>
      </li>
      <% if current_user && current_user.flat && policy(current_user.flat).edit? %>
        <li class="nav-item">
          <%= link_to edit_flat_path(current_user.flat) do %>
            <h3 class="nav-link mb-0 dashboard-link">Edit flat</h3>
          <% end %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to destroy_user_session_path, method: :delete do %>
          <h3 class="nav-link" tabindex="-1" aria-disabled="true">Sign out</h3>
        <% end %>
      </li>
    </ul>
    <% end %>
  </div>
</nav>